# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            3d Print Exchange
tagline:          'A Jekyll theme'
description:      'Build your own tools using our API to access 3dprint.nih.gov public data.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           ''
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MedicalScienceComputing/3dpx-api-docs