# Site settings
title: 3D Print Exchange
email: 3dprintexchange@nih.gov
description: > # this means to ignore newlines until "baseurl:"
  Build your own tools using our API to access 3dprint.nih.gov public data.
baseurl: "/3dpx-api-docs" # the subpath of your site, e.g. /blog/
url: "https://github.com/MedicalScienceComputing" # the base hostname & protocol for your site
twitter_username: nih3dprint
#github_username:  MedicalScienceComputing

# Build settings
markdown: kramdown
